config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  namespace :admin do
    get 'dashboard/index'
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  get 'welcome/index'
  root 'welcome#index'

  get 'tickets/thanks'
  resources :tickets, only: [:show, :new, :create] do
    resources :comments, only: [:create]
  end

  namespace :agent do
    get '/', to: 'dashboard#index'
    resources :tickets, only: [:edit, :update] do
      resources :comments, only: [:create]
    end
  end

  namespace :admin do
    get '/', to: 'dashboard#index'
    resources :tickets
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    user ||= User.new

    return unless ['admin', 'superuser'].include? user.role.to_s

    can :access, :rails_admin
    can :read, :dashboard

    if user.superuser?
      can :manage, :all
    elsif user.admin?
      can :manage, [Category, Ticket, Comment, User]

      # # Performed checks for `collection` scoped actions:
      # can :index, Model         # included in :read
      # can :new, Model           # included in :create
      # can :export, Model
      # can :history, Model       # for HistoryIndex
      # can :destroy, Model       # for BulkDelete
      #
      # # Performed checks for `member` scoped actions:
      # can :show, Model, object            # included in :read
      # can :edit, Model, object            # included in :update
      # can :destroy, Model, object         # for Delete
      # can :history, Model, object         # for HistoryShow
      # can :show_in_app, Model, object
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tickets
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :ticket
  belongs_to :user
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :category, optional: true
  belongs_to :user
  belongs_to :agent, class_name: "User", optional: true
  has_many :comments
  has_many_attached :attachments

  enum status: [ :pending, :open, :closed ]
  enum priority: [ :low, :medium, :high ]

  paginates_per 20

  after_save :assigned_ticket, if: :saved_change_to_agent_id?

  private

  def assigned_ticket
    AgentMailer.assigned_ticket(self).deliver_later
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable,
         :rememberable, :trackable, :validatable
  has_many :tickets
  has_many :comments
  enum role: [:user, :agent, :admin, :superuser]
end

app/controllers/agent/base_controller.rb
class Agent::BaseController < ApplicationController
  layout "agent"
  before_action :ensure_agent!
  before_action :query
  helper_method :status_count, :priority_count

  def status_count
    Ticket.where(agent_id: current_user.id).group(:status).count
  end

  def priority_count
    Ticket.where(agent_id: current_user.id).group(:priority).count
  end

  private

  def ensure_agent!
    raise "Unauthorized request" unless current_user && current_user.agent?
  end

  def query
    @q = Ticket.where(agent_id: current_user.id).ransack(params[:q])
  end
end

app/controllers/agent/comments_controller.rb
class Agent::CommentsController < Agent::BaseController
  before_action :get_ticket

  def create
    comment = @ticket.comments.build(comment_params)
    comment.user = current_user
    comment.save

    UserMailer.new_comment(@ticket, comment).deliver_later

    flash[:info] = "New comment created"
    redirect_to edit_agent_ticket_path(@ticket)
  end

  private

  def get_ticket
    @ticket = Ticket.find(params[:ticket_id])
  end

  def comment_params
    params.require(:comment).permit(:message)
  end
end

app/controllers/agent/dashboard_controller.rb
class Agent::DashboardController < Agent::BaseController
  def index
    @tickets = @q.result(distinct: true).order(id: :desc).page params[:page]
  end
end

app/controllers/agent/tickets_controller.rb
class Agent::TicketsController < Agent::BaseController
  def edit
    @ticket = Ticket.where(agent_id: current_user.id).includes(:comments).find(params[:id])
    @comment = Comment.new
  end

  def update
    @ticket = Ticket.find(params[:id])

    if @ticket.update(ticket_params)
      flash[:info] = "Ticket updated"
      redirect_to edit_agent_ticket_path(@ticket)
    else
      render 'edit'
    end
  end

  private

  def ticket_params
    params.require(:ticket).permit(:category_id, :status, :priority)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_path, alert: exception.message
  end
  
  before_action :authenticate_user!
  layout :layout_by_resource

  private

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :get_ticket

  def create
    comment = @ticket.comments.build(comment_params)
    comment.user = current_user
    comment.save

    AgentMailer.new_comment(@ticket, comment).deliver_later

    redirect_to ticket_path(@ticket)
  end

  private

  def get_ticket
    @ticket = Ticket.find(params[:ticket_id])
  end

  def comment_params
    params.require(:comment).permit(:message)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def show
    @ticket = current_user.tickets.includes(:comments).find(params[:id])
    @comment = Comment.new
  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.user = current_user

    if @ticket.save
      AdminMailer.new_ticket(@ticket).deliver_later
      UserMailer.new_ticket(@ticket).deliver_later
      redirect_to tickets_thanks_path
    else
      render 'new'
    end
  end

  def thanks
  end

  private

  def ticket_params
    params.require(:ticket).permit(:category_id, :name, :email, :title, :message, attachments: [])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @q = current_user.tickets.ransack(params[:q])
    @tickets = @q.result(distinct: true).order(id: :desc).page params[:page]
  end
end

app/helpers/agent/comments_helper.rb
module Agent::CommentsHelper
end

app/helpers/agent/dashboard_helper.rb
module Agent::DashboardHelper
end

app/helpers/agent/tickets_helper.rb
module Agent::TicketsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class_for key
    { success: "success", error: "danger", alert: "warning", notice: "info" }[key.to_sym] || key.to_s
  end

  def status_class_for status
    { pending: "warning", open: "success", closed: "light" }[status.to_sym] || status.to_s
  end

  def priority_class_for priority
    { low: "light", medium: "warning", high: "danger" }[priority.to_sym] || priority.to_s
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/agent/dashboard/index.html.erb
<h2 class="h4 mb-3">Tickets</h2>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Title</th>
      <th scope="col">Category</th>
      <th scope="col">Status</th>
      <th scope="col">Priority</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.name %></td>
        <td><%= ticket.email %></td>
        <td><%= ticket.title %></td>
        <td><%= ticket.category.name %></td>
        <td><span class="badge badge-<%= status_class_for(ticket.status) %>"><%= ticket.status %></span></td>
        <td>
          <% if ticket.priority.present? %>
            <span class="badge badge-<%= priority_class_for(ticket.priority) %>"><%= ticket.priority %></span>
          <% end %>
        </td>
        <td class="text-right"><%= link_to "Edit", edit_agent_ticket_path(ticket.id), class: "btn btn-sm btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @tickets, theme: 'twitter-bootstrap-4' %>

app/views/agent/tickets/edit.html.erb
<%= form_with model: @ticket, url: agent_ticket_path, local: true do |form| %>
  <table class="table table-bordered">
    <tbody>
      <tr>
        <th scope="row" class="w-25">Title</th>
        <td><%= @ticket.title %></td>
      </tr>
      <tr>
        <th scope="row">Message</th>
        <td><%= @ticket.message %></td>
      </tr>
      <tr>
        <th scope="row">Category</th>
        <td><%= form.select :category_id, options_from_collection_for_select(Category.all, :id, :name, @ticket.category.id), { include_blank: true }, { class: 'form-control' } %></td>
      </tr>
      <tr>
        <th scope="row">Status</th>
        <td><%= form.select :status, Ticket.statuses.collect { |s| s.first }, { selected: @ticket.status }, { class: 'form-control' } %></td>
      </tr>
      <tr>
        <th scope="row">Priority</th>
        <td><%= form.select :priority, Ticket.priorities.collect { |p| p.first }, { selected: @ticket.priority }, { class: 'form-control' } %></td>
      </tr>
      <tr>
        <th scope="row">Created at</th>
        <td><%= @ticket.created_at.to_s(:long) %></td>
      </tr>
      <tr>
        <th scope="row">Attachments</th>
        <td>
          <ul class="list-unstyled list-inline mb-0">
            <% @ticket.attachments.each do |file| %>
              <li class="list-inline-item">
                <a href="<%= url_for(file) %>" target="_blank"><%= image_tag(file.variant(resize_to_limit: [100, 100]), class: "img-thumbnail") %></a>
              </li>
            <% end %>
          </ul>
        </td>
      </tr>
      <tr>
        <th scope="row">Comments (<%= @ticket.comments.count %>)</th>
        <td>
          <% @ticket.comments.each do |comment| %>
            <div class="card card-body bg-light mb-3 p-3 border-0">
              <small><span class="<%= "text-primary" unless comment.user == current_user %>"><strong><%= comment.user.email %></strong></span>, <%= comment.created_at.to_s(:long) %></small><br>
              <%= comment.message %>
            </div>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
  <%= form.submit 'Submit', class: 'btn btn-primary mb-3' %>
<% end %>

<div class="card">
  <h5 class="card-header">Leave a comment</h5>
  <div class="card-body">
    <%= form_with(model: [@ticket, @comment], url: agent_ticket_comments_path(@ticket.id), local: true) do |form| %>
      <div class="form-group">
        <%= form.label :message %><br>
        <%= form.text_area :message, class: 'form-control', required: true %>
      </div>
      <%= form.submit 'Submit', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/tickets/new.html.erb
<%= render partial: "shared/error", locals: { entity: @ticket } %>

<div class="card">
  <h5 class="card-header">New Ticket</h5>
  <div class="card-body">
    <%= form_with scope: :ticket, url: tickets_path, local: true do |form| %>
      <div class="form-group">
        <%= form.label :category_id %><br>
        <%= form.select :category_id, options_from_collection_for_select(Category.all, :id, :name), { include_blank: true }, { class: 'form-control' } %>
      </div>

      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: 'form-control', required: true %>
      </div>

      <div class="form-group">
        <%= form.label :email %><br>
        <%= form.text_field :email, class: 'form-control', required: true %>
      </div>

      <div class="form-group">
        <%= form.label :title %><br>
        <%= form.text_field :title, class: 'form-control', required: true %>
      </div>

      <div class="form-group">
        <%= form.label :message %><br>
        <%= form.text_area :message, class: 'form-control', required: true %>
      </div>

      <div class="form-group">
        <%= form.label :attachments %><br>
        <%= form.file_field :attachments, multiple: true %>
      </div>

      <%= form.submit 'Submit', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/tickets/show.html.erb
<table class="table table-bordered">
  <tbody>
    <tr>
      <th scope="row" class="w-25">Title</th>
      <td><%= @ticket.title %></td>
    </tr>
    <tr>
      <th scope="row">Message</th>
      <td><%= @ticket.message %></td>
    </tr>
    <tr>
      <th scope="row">Category</th>
      <td><%= @ticket.category.name %></td>
    </tr>
    <tr>
      <th scope="row">Status</th>
      <td><span class="badge badge-<%= status_class_for(@ticket.status) %>"><%= @ticket.status %></span></td>
    </tr>
    <tr>
      <th scope="row">Created at</th>
      <td><%= @ticket.created_at.to_s(:long) %></td>
    </tr>
    <tr>
      <th scope="row">Attachments</th>
      <td>
        <ul class="list-unstyled list-inline mb-0">
          <% @ticket.attachments.each do |file| %>
            <li class="list-inline-item">
              <a href="<%= url_for(file) %>" target="_blank"><%= image_tag(file.variant(resize_to_limit: [100, 100]), class: "img-thumbnail") %></a>
            </li>
          <% end %>
        </ul>
      </td>
    </tr>
    <tr>
      <th scope="row">Comments (<%= @ticket.comments.count %>)</th>
      <td>
        <% @ticket.comments.each do |comment| %>
          <div class="card card-body bg-light mb-3 p-3 border-0">
            <small><span class="<%= "text-primary" unless comment.user == current_user %>"><strong><%= comment.user.email %></strong></span>, <%= comment.created_at.to_s(:long) %></small><br>
            <%= comment.message %>
          </div>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>

<div class="card">
  <h5 class="card-header">Leave a comment</h5>
  <div class="card-body">
    <%= form_with(model: [@ticket, @comment], local: true) do |form| %>
      <div class="form-group">
        <%= form.label :message %><br>
        <%= form.text_area :message, class: 'form-control', required: true %>
      </div>
      <%= form.submit 'Submit', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/tickets/thanks.html.erb
<div class="card text-center w-50 ml-auto mr-auto">
  <div class="card-header">
    Thank you!
  </div>
  <div class="card-body">
    <p class="card-text">Your message has been received by our support team. You will be contacted as soon as possible.</p>
    <%= link_to "Back to Home", root_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/welcome/index.html.erb
<h2 class="h4 mb-3">My Tickets</h2>

<%= search_form_for @q, url: root_path, html: { class: "form-inline mb-3" } do |f| %>
  <%= f.search_field :title_cont, class: 'form-control form-control-sm mb-2 mr-sm-2', placeholder: "Title" %>
  <%= f.select :category_id_eq, options_from_collection_for_select(Category.all, "id", "name", @q.category_id_eq), { include_blank: "Category" }, { class: 'form-control form-control-sm mb-2 mr-sm-2' } %>
  <%= f.select :status_eq, Ticket.statuses.collect {|s| [ s.first, s.last ] }, { include_blank: "Status" }, { class: 'form-control form-control-sm mb-2 mr-sm-2' } %>
  <%= f.submit 'Search', class: 'btn btn-sm btn-primary mb-2' %>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Category</th>
      <th scope="col">Status</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= link_to ticket.title, ticket_path(ticket.id) %></td>
        <td><%= ticket.category.name %></td>
        <td><span class="badge badge-<%= status_class_for(ticket.status) %>"><%= ticket.status %></span></td>
        <td class="text-right"><%= link_to "View", ticket_path(ticket.id), class: "btn btn-sm btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @tickets, theme: 'twitter-bootstrap-4' %>