config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  namespace :admin do
    get 'dashboard/index'
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  get 'welcome/index'
  root 'welcome#index'

  get 'tickets/thanks'
  resources :tickets, only: [:show, :new, :create] do
    resources :comments, only: [:create]
  end

  namespace :agent do
    get '/', to: 'dashboard#index'
    resources :tickets, only: [:edit, :update] do
      resources :comments, only: [:create]
    end
  end

  namespace :admin do
    get '/', to: 'dashboard#index'
    resources :tickets
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    user ||= User.new

    return unless ['admin', 'superuser'].include? user.role.to_s

    can :access, :rails_admin
    can :read, :dashboard

    if user.superuser?
      can :manage, :all
    elsif user.admin?
      can :manage, [Category, Ticket, Comment, User]

      # # Performed checks for `collection` scoped actions:
      # can :index, Model         # included in :read
      # can :new, Model           # included in :create
      # can :export, Model
      # can :history, Model       # for HistoryIndex
      # can :destroy, Model       # for BulkDelete
      #
      # # Performed checks for `member` scoped actions:
      # can :show, Model, object            # included in :read
      # can :edit, Model, object            # included in :update
      # can :destroy, Model, object         # for Delete
      # can :history, Model, object         # for HistoryShow
      # can :show_in_app, Model, object
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tickets
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :ticket
  belongs_to :user
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :category, optional: true
  belongs_to :user
  belongs_to :agent, class_name: "User", optional: true
  has_many :comments
  has_many_attached :attachments

  enum status: [ :pending, :open, :closed ]
  enum priority: [ :low, :medium, :high ]

  paginates_per 20

  after_save :assigned_ticket, if: :saved_change_to_agent_id?

  private

  def assigned_ticket
    AgentMailer.assigned_ticket(self).deliver_later
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable,
         :rememberable, :trackable, :validatable
  has_many :tickets
  has_many :comments
  enum role: [:user, :agent, :admin, :superuser]
end

app/controllers/agent/base_controller.rb
class Agent::BaseController < ApplicationController
  layout "agent"
  before_action :ensure_agent!
  before_action :query
  helper_method :status_count, :priority_count

  def status_count
    Ticket.where(agent_id: current_user.id).group(:status).count
  end

  def priority_count
    Ticket.where(agent_id: current_user.id).group(:priority).count
  end

  private

  def ensure_agent!
    raise "Unauthorized request" unless current_user && current_user.agent?
  end

  def query
    @q = Ticket.where(agent_id: current_user.id).ransack(params[:q])
  end
end

app/controllers/agent/comments_controller.rb
class Agent::CommentsController < Agent::BaseController
  before_action :get_ticket

  def create
    comment = @ticket.comments.build(comment_params)
    comment.user = current_user
    comment.save

    UserMailer.new_comment(@ticket, comment).deliver_later

    flash[:info] = "New comment created"
    redirect_to edit_agent_ticket_path(@ticket)
  end

  private

  def get_ticket
    @ticket = Ticket.find(params[:ticket_id])
  end

  def comment_params
    params.require(:comment).permit(:message)
  end
end

app/controllers/agent/tickets_controller.rb
class Agent::TicketsController < Agent::BaseController
  def edit
    @ticket = Ticket.where(agent_id: current_user.id).includes(:comments).find(params[:id])
    @comment = Comment.new
  end

  def update
    @ticket = Ticket.find(params[:id])

    if @ticket.update(ticket_params)
      flash[:info] = "Ticket updated"
      redirect_to edit_agent_ticket_path(@ticket)
    else
      render 'edit'
    end
  end

  private

  def ticket_params
    params.require(:ticket).permit(:category_id, :status, :priority)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_path, alert: exception.message
  end
  
  before_action :authenticate_user!
  layout :layout_by_resource

  private

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :get_ticket

  def create
    comment = @ticket.comments.build(comment_params)
    comment.user = current_user
    comment.save

    AgentMailer.new_comment(@ticket, comment).deliver_later

    redirect_to ticket_path(@ticket)
  end

  private

  def get_ticket
    @ticket = Ticket.find(params[:ticket_id])
  end

  def comment_params
    params.require(:comment).permit(:message)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def show
    @ticket = current_user.tickets.includes(:comments).find(params[:id])
    @comment = Comment.new
  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.user = current_user

    if @ticket.save
      AdminMailer.new_ticket(@ticket).deliver_later
      UserMailer.new_ticket(@ticket).deliver_later
      redirect_to tickets_thanks_path
    else
      render 'new'
    end
  end

  def thanks
  end

  private

  def ticket_params
    params.require(:ticket).permit(:category_id, :name, :email, :title, :message, attachments: [])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @q = current_user.tickets.ransack(params[:q])
    @tickets = @q.result(distinct: true).order(id: :desc).page params[:page]
  end
end

app/helpers/agent/comments_helper.rb
module Agent::CommentsHelper
end

app/helpers/agent/dashboard_helper.rb
module Agent::DashboardHelper
end

app/helpers/agent/tickets_helper.rb
module Agent::TicketsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class_for key
    { success: "success", error: "danger", alert: "warning", notice: "info" }[key.to_sym] || key.to_s
  end

  def status_class_for status
    { pending: "warning", open: "success", closed: "light" }[status.to_sym] || status.to_s
  end

  def priority_class_for priority
    { low: "light", medium: "warning", high: "danger" }[priority.to_sym] || priority.to_s
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/agent.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Rails-Helpdesk is an open source customer support application">
    <meta name="author" content="Melih Kocatürk">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="icon" href="<%= image_path("helpdesk.png") %>">
    <%= stylesheet_link_tag "dashboard" %>
    <title>Agent | Rails Helpdesk</title>
  </head>
  <body>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="/agent">Rails Helpdesk <small>Agent</small></a>
      <%= search_form_for @q, url: agent_path, html: { class: "w-100" } do |f| %>
        <%= f.search_field :title_or_message_cont, class: 'form-control form-control-dark w-100', placeholder: "Search" %>
      <% end %>
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          <% if user_signed_in? %>
            <%= link_to "Logout", destroy_user_session_path, class: "nav-link", method: :delete %>
          <% end %>
        </li>
      </ul>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <%= link_to "Dashboard", agent_path, class: "nav-link active" %>
              </li>
            </ul>

            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
              <span>Status</span>
            </h6>
            <ul class="nav flex-column mb-2">
              <% Ticket.statuses.each do |status| %>
                <li class="nav-item">
                  <%= link_to(agent_path(q: { status_eq: status.last }), class: "nav-link") do %>
                    <%= status.first.capitalize %>
                    <span class="badge badge-primary badge-pill float-right"><%= status_count[status.first] %></span>
                  <% end %>
                </li>
              <% end %>
            </ul>

            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
              <span>Priority</span>
            </h6>
            <ul class="nav flex-column mb-2">
              <% Ticket.priorities.each do |priority| %>
                <li class="nav-item">
                  <%= link_to(agent_path(q: { priority_eq: priority.last }), class: "nav-link") do %>
                    <%= priority.first.capitalize %>
                    <span class="badge badge-primary badge-pill float-right"><%= priority_count[priority.first] %></span>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4 pb-5">
          <% flash.each do |key, value| %>
            <div class="alert alert-<%= flash_class_for(key) %>" role="alert">
              <%= value %>
            </div>
          <% end %>

          <%= yield %>
        </main>
      </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Rails-Helpdesk is an open source customer support application">
    <meta name="author" content="Melih Kocatürk">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="icon" href="<%= image_path("helpdesk.png") %>">
    <title>Rails Helpdesk</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="/">
          <img src="<%= image_path("helpdesk.png") %>" width="30" height="30" class="d-inline-block align-top" alt="Helpdesk">
          Rails Helpdesk
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMain" aria-controls="navbarMain" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarMain">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <%= link_to "Home", root_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link">About</a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link">Contact</a>
            </li>
          </ul>
        </div>
        <%= link_to "New Ticket", new_ticket_path, class: "btn btn-sm btn-primary ml-2" %>
        <% if user_signed_in? %>
          <%= link_to "Logout", destroy_user_session_path, class: "btn btn-sm btn-danger ml-2", method: :delete %>
        <% end %>
      </div>
    </nav>

    <div class="container my-4">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= flash_class_for(key) %>" role="alert">
          <%= value %>
        </div>
      <% end %>

      <%= yield %>
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Rails-Helpdesk is an open source customer support application">
    <meta name="author" content="Melih Kocatürk">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="icon" href="<%= image_path("helpdesk.png") %>">
    <title>Rails Helpdesk</title>
  </head>
  <body>
    <div class="container my-4">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= flash_class_for(key) %>" role="alert">
          <%= value %>
        </div>
      <% end %>

      <%= yield %>
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_error.html.erb
<% if entity.errors.any? %>
	<div class="alert alert-danger" role="alert">
		<h4 class="alert-heading">Error!</h4>
		<ul>
			<% entity.errors.full_messages.each do |msg| %>
			   <li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>